spring:
  application:
    name: gateway-service
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    # 如果redis有密码则加上
#    password: imooc
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            # 此处可添加多个授信的地址
            allowed-origins:
              - "http://localhost:10000"
              - "*"
            # cookie, authorization认证信息
            expose-headers: "*"
            allow-credentials: true
            allowed-methods: "*"
            allowed-headers: "*"
            # 浏览器缓存时间
            max-age: 1000
      locator:
        enabled: false
        lower-case-service-id: true
      discovery:
        locator:
          enabled: false
  sleuth:
    sampler:
      probability: 1

server:
  port: 30004



## 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

hystrix:
  command:
    # 有的属性是默认值，写不写都行
    fallback2:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        errorThresholdPercentage: 50
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 10000
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 3000
