spring:
  application:
    name: zipkin-server
  cloud:
    nacos:
      discovery:
        # 可以配置多个，逗号分隔
        server-addr: localhost:8848
  main:
    allow-bean-definition-overriding: true
server:
  port: 30000

