
server:
  port: 21000
  # spring boot 2.3.X和2.2.X的一个异常处理的改动
  error:
    includeException: true
    includeStacktrace: ON_PARAM
    includeMessage: ALWAYS

spring:
  application:
    name: employee-service
  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
#      cache:
#        enabled: true
#        ttl: 35s
#        capacity: 998
#      retry:
#        enabled: true
#      service-discovery:
#        timeout: 1s
    nacos:
      discovery:
        server-addr: localhost:8848
        # employee-service也必须配置相同的group才能发起访问
        cluster-name: Cluster-2
  #        group: myGroup
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false

  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/employee_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: canal
    password: canal
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      connection-timeout: 20000
      idle-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 30000
      auto-commit: true
      pool-name: imoocHikari

# Ribbon全局配置
# 如果配置了Feign接口超时，那么ribbon超时配置则不生效
ribbon:
  # 创建RibbonClient
  eager-load:
    enabled: true
    clients: restroom-service

#  ConnectTimeout: 800 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 800 #服务请求处理超时时间（毫秒）
#  OkToRetryOnAllOperations: true #对超时请求启用重试机制
#  MaxAutoRetriesNextServer: 2 #切换重试实例的最大个数
#  MaxAutoRetries: 1 # 切换实例后重试最大次数



# 如果配置了Feign接口超时，那么ribbon超时配置则不生效
# 发送到restroom-service服务的负载均衡配置
restroom-service:
  ribbon:
    # 指定负载均衡策略为随机访问策略
    # 一般采用默认的RoundRobin负载均衡策略
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerRuleClassName: com.imooc.employee.loadbalancer.ClusterFirstRule
#    # 指定IPing策略（一般策略中不指定IPing），配合Feign使用
#    NFLoadBalancerPingClassName: com.netflix.niws.loadbalancer.NIWSDiscoveryPing
#    ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
#    ReadTimeout: 1000 #服务请求处理超时时间（毫秒）
#    OkToRetryOnAllOperations: true #对超时请求启用重试机制
#    MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
#    MaxAutoRetries: 1 # 切换实例后重试最大次数


management:
  endpoint:
    health:
      # 总是显示各个组件的actuator信息
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有endpoint
        include: '*'
  security:
    enabled: false

logging:
  level:
    ROOT: debug